name: CI Docker Frontend

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag timothedepoorter/ma-ville-et-moi-frontend

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push timothedepoorter/ma-ville-et-moi-frontend  
