name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install  

      - name: Run tests
        run: npm test  

      - name: Build application
        run: npm run build  

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/develop'  
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  
