name: CI Docker Frontend

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag timothedepoorter/ma-ville-et-moi-frontend

      - name: Push Docker image
        run: docker push timothedepoorter/ma-ville-et-moi-frontend
